// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yykoniqrnpwujttotimn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5a29uaXFybnB3dWp0dG90aW1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5Mzc4MzksImV4cCI6MjA1MjUxMzgzOX0.nZnZGqMbGJM9YKo1ocAlSFYnpf6oXkQuwfHQePW_osk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);